# configure auto-configured MultipartConfigElement
multipart:
  max-file-size: 50MB
  max-request-size: 50MB
  location: ${java.io.tmpdir}

# newer versions of spring-boot use these properties rather than above
# spring.servlet.multipart.max-file-size=128KB
# spring.servlet.multipart.max-request-size=128KB

logging:
  level.: INFO

## this disables the icon only
spring:
  mvc:
    favicon:
      enabled: false

#@Component
#@ConfigurationProperties(prefix = "my")
#public class MyConfig {
#
#    @NotNull
#    @Pattern( regexp = "my.{5}zip", message = "regex check should match my?{5}zip")
#    private String myString;
#    private long myLong;
#    private boolean myBoolean;

my:
  my-string: my12345zip
  myLong: 1234.5
  my-boolean: true
  art-string: K8s
  enable-art-string: false
